### ISSUE TITLE
package generation failure

### ISSUE THREAD

**Issue by franzholz** [franzholz/base_excel#3]
`composer run-script extension-release`
Does everything fine. However it fails at the end.

`Updating dependencies (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
  - Installing ezyang/htmlpurifier (v4.13.0): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-factory (1.0.1): Downloading (100%)         
  - Installing psr/http-client (1.0.1): Loading from cache
  - Installing psr/simple-cache (1.0.1): Downloading (100%)         
  - Installing markbaker/matrix (2.1.2): Downloading (100%)         
  - Installing markbaker/complex (2.0.0): Downloading (100%)         
  - Installing myclabs/php-enum (1.8.0): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.22.1): Loading from cache
  - Installing maennchen/zipstream-php (2.1.0): Downloading (100%)         
  - Installing phpoffice/phpspreadsheet (1.17.1): Downloading (100%)         
phpoffice/phpspreadsheet suggests installing mpdf/mpdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing dompdf/dompdf (Option for rendering PDF with PDF Writer (doesn't yet support PHP8))
phpoffice/phpspreadsheet suggests installing tecnickcom/tcpdf (Option for rendering PDF with PDF Writer (doesn't yet support PHP8))
phpoffice/phpspreadsheet suggests installing jpgraph/jpgraph (Option for rendering charts, or including charts with PDF or HTML Writers)
Writing lock file
Generating autoload files
Generated optimized autoload files (authoritative) containing 573 classes
> [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $HOME/.composer/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar
sh: /home/franz/.composer/vendor/bin/phar-composer: No such file or directory
Script [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $HOME/.composer/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar handling the extension-create-libs event returned with error code 127
Script @extension-create-libs was called via extension-build
Script @extension-build was called via extension-release
[franz@localhost base_excel]$ which composer
/usr/local/bin/composer
`

**Comment by franzholz** [comment]
I have now upgraded to composer 2. 
I run the scrpt again and get these errors.

`[franz@localhost base_excel]$ composer run-script extension-release which phar-composer
> mkdir -p Libraries/temp 'which' 'phar-composer'
> [ -f $HOME/.composer/vendor/bin/phar-composer ] || composer global require clue/phar-composer 'which' 'phar-composer'
Changed current directory to /home/franz/.config/composer

                                                                            
  [UnexpectedValueException]                                                
  Could not parse version constraint which: Invalid version string "which"  
                                                                            

```
require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

Script [ -f $HOME/.composer/vendor/bin/phar-composer ] || composer global require clue/phar-composer handling the extension-create-libs event returned with error code 1
Script @extension-create-libs was called via extension-build
Script @extension-build was called via extension-release
`
```

**Comment by cjanody** [comment]
Hi,
There is an error with your last command, it should not contain `which phar-composer`. However, the real problem is the location of phar-composer on your operating system. We use `ddev` in our team to work around this issue.
On my system phar-composer is located here `$HOME/.config/composer/vendor/bin/phar-composer`. Can you try this path or setup a ddev environment?

**Comment by franzholz** [comment]
I have a global installation on my system .This should also be supported.

    [root@localhost bin]# pwd
    /usr/local/bin
    [root@localhost bin]# ls -l
    total 4064
    lrwxrwxrwx 1 root root      13 Apr 27 15:23 composer -> composer.phar*
    -rwxr-xr-x 1 root root 2216568 Apr 27 15:10 composer.phar*
    -rw-r--r-- 1 root root 1940741 Apr 27 15:37 phar-composer-1.2.0.phar
    lrwxrwxrwx 1 root root      24 Apr 27 15:38 phar-composer.phar -> phar-composer-1.2.0.phar
    [root@localhost bin]# 
`

Which folder structure is required to run the composer scripts?
Must this folder path exist?

    Build/Web/typo3conf/ext/base_excel

**Comment by cjanody** [comment]
You do not need to do special things:
![image](https://user-images.githubusercontent.com/3030277/116261977-28439880-a746-11eb-988b-43eba3fafe92.png)

![image](https://user-images.githubusercontent.com/3030277/116263145-2201ec00-a747-11eb-8268-b3c8e646021c.png)

**Comment by franzholz** [comment]
Shouldn't this be changed?

    $HOME/.composer/vendor/bin/phar-composer  

I always use the composer globally. So every user can use it.

    [franz@localhost base_excel (master)]$ cd -
    /usr/local/bin
    [franz@localhost bin]$ ls -l
    total 4064
    lrwxrwxrwx 1 root root      13 Apr 27 15:23 composer -> composer.phar*
    -rwxr-xr-x 1 root root 2216568 Apr 27 15:10 composer.phar*
    lrwxrwxrwx 1 root root      24 Apr 27 17:16 phar-composer -> phar-composer-1.2.0.phar
    -rw-r--r-- 1 root root 1940741 Apr 27 15:37 phar-composer-1.2.0.phar
    lrwxrwxrwx 1 root root      24 Apr 27 15:38 phar-composer.phar -> phar-composer-1.2.0.phar

The $PATH variable should have all paths where executable files can be found.

**Comment by cjanody** [comment]
phar-composer is installed by the script itself via `composer global require clue/phar-composer`. Using composer to install it will place it in your $HOME.

**Comment by franzholz** [comment]
Which script installs the "phar-composer"? What do you mean?

Ok, the composer.json contains this part:

    composer global require clue/phar-composer

However why is it not executed in my case, where no file `$HOME/.composer/vendor/bin/phar-composer` exists?

Could you modify the "composer.json" in a way which supports a global installation as well? $HOME should not be needed for a global installation.

**Comment by cjanody** [comment]
I will check this as soon as possible. Maybe next week.
